export const transportData = [
  {
    date: "1/10/2022",
    Vehicletype: "Plough",
    from: "Kothanur",
    to: "Hebbal",
    id: "9",
  },
  {
    date: "1/09/2022",
    Vehicletype: "Tractor",
    from: "Kalyannagar",
    to: "Maruti Nagar",
    id: "10",
  },
  {
    date: "10/10/2022",
    Vehicletype: "Miller",
    from: "BS road",
    to: "Richmond",
    id: "11",
  },
  {
    date: "20/04/2022",
    Vehicletype: "Plough",
    from: "Kothanur",
    to: "Electonic city",
    id: "12",
  },
  {
    date: "13/2/2022",
    Vehicletype: "Reaper",
    from: "Rp main",
    to: "Mg main",
    id: "18",
  },
  {
    date: "11/10/2022",
    Vehicletype: "Plough",
    from: "SG palya",
    to: "BTM layout",
    id: "17",
  },
  {
    date: "16/20/2022",
    Vehicletype: "Tractor",
    from: "Hosur",
    to: "Whitefield",
    id: "32",
  },
];
