export const detailData = [
  {
    name: "Malik",
    crop: "whaet",
    taluk: "Kothanur",
    address: "Hebbal",
    quantity: "9",
    phonenumber: "9893612345",
  },
  {
    name: "Alen",
    crop: "rice",
    taluk: "Kalyannagar",
    address: "Maruti Nagar",
    quantity: "2",
    phonenumber: "9875432627",
  },
  {
    name: "Harsh",
    crop: "corns",
    taluk: "BS road",
    address: "Richmond",
    quantity: "11",
    phonenumber: "8975434272",
  },
  {
    name: "Vardhan",
    crop: "whaet",
    taluk: "Kothanur",
    address: "Electonic city",
    quantity: "12",
    phonenumber: "9862528271",
  },
  {
    name: "Raj",
    crop: "onion",
    taluk: "Rp main",
    address: "Mg main",
    quantity: "18",
    phonenumber: "96253728272",
  },
  {
    name: "Ram",
    crop: "potato",
    taluk: "SG palya",
    address: "BTM layout",
    quantity: "17",
    phonenumber: "8756463531",
  },
  {
    name: "Reet",
    crop: "onion",
    taluk: "Hosur",
    address: "Whitefield",
    quantity: "32",
    phonenumber: "9898976544",
  },
];
